// AUTO-GENERATED by scripts/build.py from data/family-tree.ged
// Do not edit by hand. Edit the .ged file and re-run the build.
window.TREE = {
  "meta": {
    "generated_from": "data/family-tree.ged",
    "header": {
      "date": "11 JUL 2026",
      "note": "This GEDCOM is the canonical, version-controlled source of truth for the\nHutson family tree. Every genealogical fact carries a SOUR citation that\npoints to a SOUR record at the bottom of the file. Custom tags used:\n  _URL  = web address of the source\n  _CONF = confidence level (Primary / Secondary / Tentative / Provided)\n  _ACC  = date the source was accessed\nRun scripts/build.py after editing this file to regenerate the UI data."
    },
    "counts": {
      "individuals": 1,
      "families": 0,
      "sources": 3
    }
  },
  "individuals": {
    "I1": {
      "id": "I1",
      "names": [
        {
          "full": "Miles Hutson",
          "given": "Miles",
          "surname": "Hutson"
        }
      ],
      "sex": "M",
      "events": [
        {
          "date": "12 AUG 1993",
          "place": null,
          "value": null,
          "citations": [
            {
              "source": "S1",
              "page": "Personal communication, 2026-07-11",
              "conf": "Provided",
              "note": null
            }
          ],
          "type": "BIRT",
          "label": "Birth"
        },
        {
          "date": "2026",
          "place": "San Francisco, California, USA",
          "value": null,
          "citations": [
            {
              "source": "S1",
              "page": null,
              "conf": "Provided",
              "note": null
            }
          ],
          "type": "RESI",
          "label": "Residence"
        },
        {
          "date": "FROM 2016 TO 2022",
          "place": "Austin / Mountain View, California, USA",
          "value": null,
          "citations": [
            {
              "source": "S2",
              "page": null,
              "conf": "Secondary",
              "note": null
            }
          ],
          "type": "RESI",
          "label": "Residence"
        },
        {
          "date": null,
          "place": null,
          "value": "B.S. Computer Science, University of Texas at Austin (2012-2016); Phi Beta Kappa",
          "citations": [
            {
              "source": "S2",
              "page": null,
              "conf": "Secondary",
              "note": null
            }
          ],
          "type": "EDUC",
          "label": "Education"
        },
        {
          "date": null,
          "place": null,
          "value": "M.S. Computer Science, Stanford University (2021-2024)",
          "citations": [
            {
              "source": "S2",
              "page": null,
              "conf": "Secondary",
              "note": null
            }
          ],
          "type": "EDUC",
          "label": "Education"
        },
        {
          "date": null,
          "place": null,
          "value": "Senior Software Engineer (Machine Learning) - Waymo; previously Google Health",
          "citations": [
            {
              "source": "S2",
              "page": null,
              "conf": "Secondary",
              "note": null
            }
          ],
          "type": "OCCU",
          "label": "Occupation"
        }
      ],
      "notes": [
        "Subject of this research and the person who commissioned the tree. Rode the\nTexas 4000 charity bicycle ride (Austin, TX to Anchorage, AK) for cancer\nresearch. Former Digital Projects Lead at The Daily Texan and data-visualization\ncontributor to The Texas Tribune."
      ],
      "famc": [],
      "fams": [],
      "name": "Miles Hutson"
    }
  },
  "families": {},
  "sources": {
    "S1": {
      "id": "S1",
      "title": "Personal communication from Miles Hutson",
      "author": "Miles Hutson",
      "publication": "Direct statement to the research assistant",
      "url": null,
      "confidence": "Provided",
      "accessed": "2026-07-11",
      "note": "First-hand information supplied by the subject himself: full name, date of\nbirth (12 August 1993), and current city of residence (San Francisco)."
    },
    "S2": {
      "id": "S2",
      "title": "Miles Hutson - Personal Website & Professional Profiles",
      "author": "Miles Hutson",
      "publication": "mileshutson.com; LinkedIn; The Texas Tribune staff page",
      "url": "https://www.mileshutson.com/",
      "confidence": "Secondary",
      "accessed": "2026-07-11",
      "note": "Publicly published biographical and career information. Corroborated across\nmileshutson.com, linkedin.com/in/mileshutson, and texastribune.org."
    },
    "S3": {
      "id": "S3",
      "title": "Hutson surname - etymology and history",
      "author": null,
      "publication": "WikiTree surname study; House of Names; archives.com",
      "url": "https://www.wikitree.com/genealogy/HUTSON",
      "confidence": "Secondary",
      "accessed": "2026-07-11",
      "note": "English patronymic surname derived from the medieval given name \"Hudde\"\n(a pet form of Hugh, \"heart/mind,\" or a variant of Hudson). First recorded\nas William Hudde in the 1273 Hundred Rolls of Cambridgeshire, England.\nThis is general surname background, NOT proof of Miles Hutson's specific line."
    }
  }
};
